
@protocol = https
@port = 5001
@host = localhost

@baseUrl = {{protocol}}://{{host}}:{{port}}

GET {{baseUrl}}/api/users

###

GET {{baseUrl}}/api/users/1

###

POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "FirstName":"Marcin",
    "LastName":"Sulecki",
    "Email": "marcin.sulecki@sulmar.pl"
}

###

PUT {{baseUri}}/api/users/1
Content-Type: application/json

{
    "Id":1,
    "FirstName":"Marcin",
    "LastName":"Sulecki",
    "Email": "marcin.sulecki@sulmar.pl"
}

###

DELETE {{baseUri}}/api/users/1

###